### ISSUE TITLE
How to add two toggle switch ?

### ISSUE THREAD

**Issue by mechn34** [dmadison/Sim-Racing-Arduino#13]
Hello, I want to add two toggle switches but I can't. It should be the same as adding a button, but I didn't get any results when I followed the instructions. I made the part in the link with a 3D printer, but I cannot add it to the code. Can you help me ? 

I need to be able to use these buttons constantly, regardless of the gears, because they will be the transfer and boost gear.

[Shifter](https://tr.aliexpress.com/item/1005005554399947.html?spm=a2g0o.productlist.main.39.325e506bobKmL6&algo_pvid=d5ecc236-625b-43b3-8475-af2f929b0e67&algo_exp_id=d5ecc236-625b-43b3-8475-af2f929b0e67-19&pdp_npi=4%40dis%21TRY%211637.79%211064.68%21%21%2157.24%21%21%402101f4a016948910339125803ef988%2112000033520965462%21sea%21TR%210%21AS&curPageLogUid=5QtiKjQk3zcg)

#8 

@dmadison @kaamburoow

**Comment by kaamburoow** [comment]
First should the buttons be debounced? I may find my old sketch and help you.

**Comment by mechn34** [comment]
> First should the buttons be debounced? I may find my old sketch and help you.

[Shifter Image](https://pphalmar.pl/galeria_Zdj/org/20170824070011_3.JPG ) 

Gears 1,2,3 when the Toggle Switch is in the 0 position.
Gears 4,5,6 when the Toggle Switch is in the 1 position.

I can use two toggle switch.

**Comment by dmadison** [comment]
Hello. Could you please elaborate on the problem you're experiencing? What do you mean you "can't" modify the code?

**Comment by mechn34** [comment]
> Hello. Could you please elaborate on the problem you're experiencing? What do you mean you "can't" modify the code?

I would like to explain exactly what I want with a certain section of the YouTube video below.

https://youtu.be/jR7MFROz66o?t=298

I want the extra buttons and toggle switches to work independently of the gears. Like at the end of the video.

**Comment by dmadison** [comment]
The examples in this library which implement USB joystick features use the [Arduino Joystick Library](https://github.com/MHeironimus/ArduinoJoystickLibrary/). Please refer to the examples in that library for information on how to connect buttons and switches to the joystick output.
