### ISSUE TITLE
Logitech G27 Shift Reverse Gear Button 7 Input Not Recognized

### ISSUE THREAD

**Issue by InherentResolve** [dmadison/Sim-Racing-Arduino#9]
Following your YouTube tutorial to convert the Logitech G27 shifter into a standalone unit (https://www.youtube.com/watch?v=ngXsOidoWhI), the reverse gear/button 7 input is not recognized.

**Comment by dmadison** [comment]
Hello. Please double-check your wiring, especially the reverse gear wire on pin 2 and the power jumper between pins 9 and 3. Are you using the suggested parts in the video description?

If you're still having issues, try this simple test script and share your results:

```cpp
const int Pin = 2;

void setup() {
    Serial.begin(115200);
    pinMode(Pin, INPUT);
}

void loop() {
    Serial.println(digitalRead(Pin) ? "Reverse" : "_");
}
```

**Comment by InherentResolve** [comment]
Just went through the tutorial again. Double-checked all connections and all are connected properly. I'm using an Arduino brand Leonardo board. All connections are tight and secure. I ran the test script on SerialMonitor and the results are a constant Reverse.

**Comment by dmadison** [comment]
>I ran the test script on SerialMonitor and the results are a constant Reverse.

Is that true regardless of the gear the shifter is in? If that's the case then the only possibility is a wiring issue. I'd recommend checking with a multimeter if you have one handy.

Are you using the linked DB9 adapters?

**Comment by InherentResolve** [comment]
Yes, that was the case before I even touched the shifter after I started the Serial Monitor. I started the Serial Monitor with the shifter in the neutral position and the Serial Monitor kept scrolling Reverse.

**Comment by InherentResolve** [comment]
Not sure what you mean by linked adapter. It's a single male adapter made to receive one female connection and nothing else. It's a different brand than the one you have linked in the description.

**Comment by dmadison** [comment]
>It's a different brand than the one you have linked in the description

If that's the case I would check that the pinout of the DB9 connector matches the silkscreen. The connector I linked in the description of the video is the one I used, some other connectors are known to have silkscreen labels that don't match the pin numbers.

If that checks out and you are certain that the connections are correct between the shifter and the Arduino, the next step is to unfortunately disassemble the shifter and measure continuity through the entire chain - from the PCB traces through to the Arduino.

**Comment by InherentResolve** [comment]
I'll give the DB9 adapter you used a try. When I plug the shifter into the original G27 wheel, it performs normally through all gears. It's when used with the DB9 connector to the Leonardo that the issue appears.

**Comment by InherentResolve** [comment]
Earliest delivery for the one you used is end of March. Do you have another you recommend with a faster delivery time?

**Comment by dmadison** [comment]
>Earliest delivery for the one you used is end of March. Do you have another you recommend with a faster delivery time?

I don't, unfortunately.

Just about any DB9 connector should work. As long as it's making a solid electrical connection to the mating connector you can use a multimeter to check and swap any mislabeled pins.

>When I plug the shifter into the original G27 wheel, it performs normally through all gears. It's when used with the DB9 connector to the Leonardo that the issue appears.

I know I'll sound like a broken record here, but that leaves only the wiring as a possible culprit. That simplified script showed that the 'reverse' signal isn't getting to the board, so nothing in the software / library is having an effect.

I'm afraid there's nothing more I can do to help. I'm going to close this issue, as your problem is not related to the software library. Feel free to reopen it if you're still having issues after getting the connections working.
